---
# handlers file for netzwirt.http-haproxy

- name: restart haproxy
  service: 
    name: haproxy 
    state: restarted


- name: reload haproxy
  service: 
    name: haproxy 
    state: reloaded
    
    
- name: restart xinetd
  service: 
    name: haproxy 
    state: restarted
